In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_rows', 500)
pd.set_option('display.show_dimensions', True)
pd.set_option('display.max_columns', None)
%matplotlib inline
plt.style.use('fivethirtyeight')

In [2]:
# Load in the dataset
merged_data = pd.read_csv('/home/yungshun/workspace/py/sklearn-aftygh-respiratory-therapy/datasets/merged_data.csv')

In [3]:
merged_data.head()

,病歷號,收件日期,收件時間,Temperature,pH,pCO2,pO2,HCO3,TCO2,ABE,SBE,SBC,SAT,Na,K,Mg,Cl,BUN (B),Creatinine(B),mode,peep,fio2,tidal volume,respiratory rate,minute ventilation,spo2
0,114400,20130125,714,37.0,7.267,59.0,459.4,27.1,28.9,-0.6,-0.1,24.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,114400,20130125,1027,37.0,7.281,59.3,94.0,28.1,30,0.5,1.1,24.8,96.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114400,20130125,1250,37.0,7.287,54.0,136.5,26.0,27.6,-1.1,-0.9,23.5,98.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,114400,20130125,1255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.4,4.71,NaN,NaN,48.1,2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,114400,20130126,959,37.0,7.183,81.7,53.2,31.0,33.5,0.6,2.4,24.4,76.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
merged_data.shape

(12490, 26)

In [5]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12490 entries, 0 to 12489
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 12490 non-null  int64
 1   收件日期                12490 non-null  int64
 2   收件時間                12490 non-null  int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1871 non-null   object
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  8940 non-null   float64
 14  K                   9526 non-null   float64
 15  Mg                  614 non-null    float64
 16  Cl                  535 non-null    float64
 17  BUN (B)             5925 non-null   object
 18  Creatinine(B)       6944 non-null   object
 19  mode                4658 non-null   object
 20  peep                4458 non-null   float64
 21  fio2                4591 non-null   object
 22  tidal volume        4130 non-null   object
 23  respiratory rate    4458 non-null   object
 24  minute ventilation  4168 non-null   object
 25  spo2                4615 non-null   object
dtypes: float64(14), int64(3), object(9)
memory usage: 2.5+ MB

In [6]:
merged_data.isnull().sum()

病歷號                       0
收件日期                      0
收件時間                      0
Temperature           10619
pH                    10619
pCO2                  10619
pO2                   10619
HCO3                  10619
TCO2                  10619
ABE                   10619
SBE                   10619
SBC                   10619
SAT                   10619
Na                     3550
K                      2964
Mg                    11876
Cl                    11955
BUN (B)                6565
Creatinine(B)          5546
mode                   7832
peep                   8032
fio2                   7899
tidal volume           8360
respiratory rate       8032
minute ventilation     8322
spo2                   7875
Length: 26, dtype: int64

In [7]:
merged_data['Na'] = merged_data.groupby(['病歷號', '收件日期'])['Na'].transform(lambda x: x.fillna(method='bfill'))
merged_data['K'] = merged_data.groupby(['病歷號', '收件日期'])['K'].transform(lambda x: x.fillna(method='bfill'))
merged_data['Mg'] = merged_data.groupby(['病歷號', '收件日期'])['Mg'].transform(lambda x: x.fillna(method='bfill'))
merged_data['Cl'] = merged_data.groupby(['病歷號', '收件日期'])['Cl'].transform(lambda x: x.fillna(method='bfill'))
merged_data['BUN (B)'] = merged_data.groupby(['病歷號', '收件日期'])['BUN (B)'].transform(lambda x: x.fillna(method='bfill'))
merged_data['Creatinine(B)'] = merged_data.groupby(['病歷號', '收件日期'])['Creatinine(B)'].transform(lambda x: x.fillna(method='bfill'))
merged_data.head()

,病歷號,收件日期,收件時間,Temperature,pH,pCO2,pO2,HCO3,TCO2,ABE,SBE,SBC,SAT,Na,K,Mg,Cl,BUN (B),Creatinine(B),mode,peep,fio2,tidal volume,respiratory rate,minute ventilation,spo2
0,114400,20130125,714,37.0,7.267,59.0,459.4,27.1,28.9,-0.6,-0.1,24.0,100.0,141.4,4.71,NaN,NaN,48.1,2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,114400,20130125,1027,37.0,7.281,59.3,94.0,28.1,30,0.5,1.1,24.8,96.0,141.4,4.71,NaN,NaN,48.1,2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,114400,20130125,1250,37.0,7.287,54.0,136.5,26.0,27.6,-1.1,-0.9,23.5,98.7,141.4,4.71,NaN,NaN,48.1,2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,114400,20130125,1255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,141.4,4.71,NaN,NaN,48.1,2.05,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,114400,20130126,959,37.0,7.183,81.7,53.2,31.0,33.5,0.6,2.4,24.4,76.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
merged_data_dropna = merged_data.dropna(subset=['Temperature', 'pH', 'pCO2', 'pO2', 'HCO3', 'TCO2', 'ABE', 'SBE', 'SBC', 'SAT'], how='all')
merged_data_dropna.shape

(1871, 26)

In [9]:
merged_data_tco2 = merged_data_dropna['TCO2'].value_counts().sort_index().to_frame()
merged_data_tco2

          TCO2
--------     1
1.8          1
10           1
10.1         1
10.3         2
10.4         1
10.7         3
10.9         3
11           1
11.6         1
11.7         1
11.8         2
11.9         1
12           2
12.1         1
12.3         3
12.4         1
12.5         2
12.6         1
12.7         2
12.8         1
12.9         1
13           2
13.1         1
13.3         1
13.5         1
13.7         3
13.8         1
14           1
14.2         4
14.3         3
14.4         1
14.5         1
14.6         2
14.7         3
14.8         2
14.9         3
15.1         4
15.2         4
15.3         1
15.4         3
15.5         3
15.6         1
15.7         3
15.8         3
15.9         2
16.1         2
16.2         3
16.3         6
16.4         3
16.5         6
16.6         5
16.7         6
16.8         8
16.9         8
17           4
17.1         4
17.2         4
17.3         4
17.4         6
17.5         4
17.6         2
17.7         3
17.8         4
17.9         5
18           8
18.1         7
18.2         6
18.3         6
18.4         1
18.5        11
18.6         2
18.7         4
18.8         9
18.9         9
19           6
19.1         5
19.2         8
19.3        10
19.4        10
19.5        12
19.6         6
19.7         7
19.8        16
19.9        12
20           7
20.1         8
20.2         9
20.3         6
20.4         9
20.5        11
20.6        15
20.7         2
20.8        11
20.9         8
21          10
21.1         7
21.2         4
21.3         8
21.4        13
21.5        11
21.6         7
21.7        11
21.8        10
21.9         8
22          23
22.1        10
22.2        11
22.3        10
22.4        16
22.5        13
22.6        10
22.7         6
22.8        11
22.9         8
23           9
23.1         9
23.2        12
23.3        11
23.4         7
23.5        21
23.6        11
23.7        12
23.8        11
23.9        15
24           9
24.1        10
24.2         9
24.3        16
24.4        14
24.5        11
24.6        11
24.7        14
24.8        13
24.9         8
25          15
25.1        12
25.2        13
25.3         8
25.4         8
25.5        11
25.6        17
25.7        12
25.8        14
25.9        10
26          12
26.1        12
26.2        14
26.3        13
26.4        12
26.5        11
26.6         9
26.7        10
26.8        14
26.9         8
27          13
27.1        10
27.2         3
27.3         7
27.4        10
27.5        12
27.6        10
27.7        13
27.8        11
27.9         7
28          12
28.1        16
28.2        12
28.3         7
28.4        15
28.5         8
28.6        14
28.7         3
28.8        14
28.9        10
29           9
29.1         7
29.2        10
29.3        16
29.4         8
29.5         5
29.6        12
29.7        10
29.8        11
29.9         5
3.5          1
30           8
30.1        11
30.2         4
30.3         8
30.4         7
30.5         9
30.6        13
30.7        10
30.8         9
30.9         9
31           5
31.1        10
31.2         9
31.3         8
31.4        10
31.5         8
31.6         5
31.7         6
31.8         7
31.9         6
32           9
32.1        10
32.2         7
32.3         4
32.4         8
32.5         4
32.6         2
32.7         2
32.8         9
32.9         7
33           7
33.1         3
33.2         1
33.3         6
33.4         7
33.5         4
33.6         5
33.7         3
33.8         6
33.9         3
34           3
34.2         2
34.3         3
34.4         1
34.5         6
34.6         2
34.7         4
34.8         3
34.9         2
35           5
35.1         3
35.2         7
35.3         4
35.4         2
35.5         3
35.6         3
35.7         3
35.8         4
35.9         5
36           2
36.1         1
36.2         3
36.3         3
36.4         2
36.5         2
36.7         1
36.8         2
36.9         3
37           2
37.1         4
37.2         2
37.3         2
37.4         2
37.5         1
37.6         1
37.7         1
38           2
38.1         3
38.2         1
38.4         2
38.5         1
38.8         1
38.9         2
39           1
39.1         1
39.2         1
39.3         2
39.4         2
39.6         1
39.7         1
39.8         4
4            1
40           1
40.1         2
40.2         3
40.3         4
40.6         2
40.7         1
40.8         1
41           1
41.1         1
41.2         1
41.5         1
41.8         1
42           3
42.1         4
42.2         3
42.3         2
42.7         1
42.8         2
42.9         1
43.4         2
43.7         2
43.8         1
43.9         2
44.4         2
44.6         1
44.7         1
45           1
45.2         2
45.4         1
45.6         1
45.8         1
45.9         1
46.1         1
46.2         2
46.4         1
46.9         1
47           3
47.2         1
47.3         1
48.5         1
48.9         2
5.7          1
52.2         1
52.3         1
53.4         1
6.1          2
6.3          1
60           1
61.2         1
7.1          1
7.3          1
7.4          1
7.6          1
7.8          1
7.9          1
8            1
9            3
9.5          1
9.9          1

[337 rows x 1 columns]

In [10]:
merged_data_tco2.index[0]

'--------'

In [11]:
merged_data_dropna['TCO2'].replace({'--------': None}, inplace=True)
merged_data_dropna['TCO2'] = pd.to_numeric(merged_data_dropna['TCO2'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    object
 18  Creatinine(B)       583 non-null    object
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    object
 22  tidal volume        359 non-null    object
 23  respiratory rate    486 non-null    object
 24  minute ventilation  331 non-null    object
 25  spo2                531 non-null    object
dtypes: float64(15), int64(3), object(8)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/3396192219.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['TCO2'].replace({'--------': None}, inplace=True)
/tmp/ipykernel_19485/3396192219.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['TCO2'] = pd.to_numeric(merged_data_dropna['TCO2'])

In [12]:
merged_data_bun_b = merged_data_dropna['BUN (B)'].value_counts().sort_index().to_frame()
merged_data_bun_b

          BUN (B)
     < 1       10
1.2             1
1.3             1
1.4             2
1.5             3
1.6             1
10              3
10.1            1
10.4            2
10.5            3
100.7           1
102.5           1
102.7           1
103.9           1
106.9           2
107.8           1
109.7           1
109.9           1
11              1
11.1            2
11.2            2
11.3            1
11.4            2
11.5            2
11.6            4
11.7            3
110             1
111             2
113.4           1
116.5           1
118.2           1
119.5           1
12.1            4
12.2            1
12.3            2
12.4            1
12.6            3
12.8            2
128             1
13              5
13.1            2
13.2            1
13.4            2
13.5            1
13.6            1
13.7            1
13.8            2
131.9           1
134.3           1
14              1
14.1            1
14.3            1
14.4            3
14.7            1
14.8            2
14.9            1
143.4           1
144.4           1
15              2
15.1            1
15.2            2
15.3            2
15.6            1
15.7            1
15.8            3
15.9            7
16              2
16.1            1
16.3            6
16.4            1
16.5            3
16.6            1
16.7            1
16.8            5
16.9            2
17              1
17.1            1
17.2            2
17.3            3
17.4            1
17.5            3
18              3
18.1            2
18.3            1
18.4            2
18.5            2
18.7            1
18.8            3
19              1
19.2            2
19.5            2
19.8            2
2.1             1
2.2             1
2.4             2
2.8             1
20              1
20.1            1
20.5            3
20.6            1
20.7            1
21              1
21.1            1
21.2            1
21.3            3
21.4            1
22              1
22.2            2
22.5            2
22.6            1
22.7            1
22.9            2
23              1
23.1            2
23.2            1
23.3            3
23.4            1
23.5            3
23.8            1
24              1
24.1            3
24.3            1
24.6            1
24.7            2
24.8            1
24.9            1
25              2
25.1            2
25.2            2
25.4            1
25.5            1
25.6            1
25.9            1
252             1
26.1            1
26.3            1
26.5            1
26.7            2
27              2
27.1            1
27.3            1
27.4            1
27.5            1
27.6            1
27.7            1
27.9            1
28.1            3
28.4            2
28.5            1
28.9            2
29.3            1
29.5            1
29.8            1
29.9            1
3.1             1
3.5             2
3.6             1
3.8             2
30.4            1
30.9            1
31.4            1
31.7            1
32              1
32.4            1
32.9            1
33.4            1
33.5            2
33.6            1
34              1
34.3            1
34.5            2
34.8            1
35              1
35.1            2
35.2            2
35.3            1
35.4            2
35.6            1
36              3
36.2            3
36.5            1
37.4            1
37.5            1
37.7            1
37.8            1
37.9            1
38              1
38.1            2
38.9            3
39.3            1
39.4            1
4.1             2
4.2             2
4.3             1
4.5             1
4.6             1
4.7             1
4.8             1
4.9             1
40.1            5
40.4            1
40.9            1
41              1
41.1            2
42              1
42.8            1
43              1
43.6            1
43.8            1
44.2            1
44.9            1
45.1            1
45.7            1
46.4            1
46.7            1
46.8            1
47.3            1
47.6            1
47.8            1
48.1            3
48.2            1
48.9            1
49.4            1
5.1             5
5.2             1
5.3             3
5.4             1
5.8             1
5.9             2
50              1
50.5            1
50.8            1
50.9            2
51.8            1
51.9            1
52.4            2
52.9            2
53              2
53.2            1
53.4            1
53.6            2
53.9            1
54.1            1
54.2            1
54.7            2
55.3            1
55.6            1
56              1
56.1            1
56.2            1
56.9            1
57.1            1
57.4            1
57.8            2
58.3            2
58.8            1
59.4            1
6.1             1
6.2             1
6.3             1
6.8             1
61.6            1
62.5            2
62.6            1
62.8            1
63.4            1
64.7            1
64.9            2
66.7            3
66.9            1
67.2            1
68.2            1
68.7            1
7               1
7.2             1
7.4             1
7.6             1
7.7             4
70              2
70.9            1
71.3            1
73              2
74              1
74.1            1
74.4            1
74.5            1
74.8            2
75              1
76.7            1
77.2            1
77.4            1
77.5            1
77.7            2
79.6            1
8               1
8.1             2
8.3             2
8.4             1
8.6             1
8.7             5
8.8             1
8.9             1
80.7            1
80.9            1
81.6            1
82.1            2
82.2            1
82.8            1
82.9            1
83.3            1
84              1
85.2            1
85.3            1
85.5            1
87.7            2
88.8            2
9               1
9.1             3
9.2             2
9.4             1
9.5             1
9.7             2
9.8             1
9.9             3
90.1            1
91.9            3
92.3            1
92.5            1
92.6            2
93.6            1
94.5            1
94.7            1
97.6            1

[333 rows x 1 columns]

In [13]:
merged_data_bun_b.index[0]

'     < 1'

In [14]:
merged_data_dropna['BUN (B)'].replace({'     < 1': 1}, inplace=True)
merged_data_dropna['BUN (B)'] = pd.to_numeric(merged_data_dropna['BUN (B)'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    object
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    object
 22  tidal volume        359 non-null    object
 23  respiratory rate    486 non-null    object
 24  minute ventilation  331 non-null    object
 25  spo2                531 non-null    object
dtypes: float64(16), int64(3), object(7)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/840247232.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['BUN (B)'].replace({'     < 1': 1}, inplace=True)
/tmp/ipykernel_19485/840247232.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['BUN (B)'] = pd.to_numeric(merged_data_dropna['BUN (B)'])

In [15]:
merged_data_creatinine_b = merged_data_dropna['Creatinine(B)'].value_counts().sort_index().to_frame()
merged_data_creatinine_b

          Creatinine(B)
   < 0.1              1
0.1                   1
0.12                  1
0.15                  1
0.18                  1
0.2                   1
0.21                  1
0.22                  1
0.23                  1
0.25                  1
0.26                  4
0.27                  2
0.28                  2
0.29                  4
0.3                   1
0.31                  5
0.33                  2
0.36                  2
0.37                  3
0.38                  5
0.39                  3
0.4                   8
0.41                  6
0.42                  3
0.43                  4
0.44                  2
0.46                  2
0.47                  4
0.48                  4
0.49                  4
0.5                   6
0.51                  4
0.52                  4
0.53                  3
0.54                  2
0.55                  4
0.56                  2
0.57                  3
0.58                  7
0.59                  2
0.6                   5
0.61                  2
0.62                  4
0.63                  6
0.64                  4
0.65                  3
0.66                  4
0.67                  2
0.68                  2
0.69                  3
0.7                   9
0.71                  4
0.72                  7
0.73                  8
0.74                  2
0.76                  4
0.77                  3
0.78                  3
0.79                  2
0.8                   5
0.81                  1
0.82                  6
0.83                  3
0.84                  8
0.85                  4
0.86                  3
0.87                  1
0.88                  3
0.89                  7
0.9                   5
0.91                  1
0.92                  2
0.93                  4
0.94                  4
0.95                  3
0.96                  4
0.98                  3
0.99                  3
1                     2
1.01                  1
1.03                  4
1.04                  4
1.05                  2
1.06                  2
1.07                  5
1.08                  1
1.09                  1
1.1                   4
1.11                  4
1.12                  2
1.13                  3
1.14                  1
1.15                  1
1.16                  4
1.17                  3
1.18                  1
1.19                  3
1.2                   4
1.21                  4
1.22                  2
1.23                  2
1.25                  5
1.26                  2
1.28                  4
1.3                   2
1.31                  2
1.32                  1
1.33                  4
1.34                  2
1.35                  3
1.36                  3
1.37                  2
1.38                  3
1.39                  2
1.41                  3
1.43                  2
1.44                  3
1.47                  3
1.48                  1
1.5                   1
1.51                  1
1.52                  2
1.53                  1
1.55                  3
1.56                  1
1.57                  1
1.59                  1
1.61                  1
1.62                  3
1.63                  5
1.64                  1
1.65                  1
1.67                  1
1.69                  3
1.7                   1
1.73                  1
1.74                  1
1.76                  3
1.77                  3
1.78                  1
1.79                  3
1.81                  1
1.83                  1
1.86                  1
1.89                  2
1.9                   2
1.92                  1
1.93                  1
1.95                  1
1.99                  1
10.91                 1
11.03                 1
12.34                 1
13.76                 1
2                     3
2.01                  1
2.03                  1
2.05                  4
2.06                  3
2.08                  1
2.09                  1
2.1                   1
2.11                  1
2.14                  1
2.16                  1
2.19                  2
2.2                   2
2.21                  2
2.23                  1
2.24                  1
2.26                  1
2.27                  1
2.32                  1
2.34                  2
2.4                   1
2.45                  2
2.48                  2
2.49                  2
2.5                   1
2.69                  1
2.7                   1
2.72                  1
2.73                  1
2.74                  1
2.84                  1
2.85                  1
2.86                  1
2.89                  1
2.9                   1
2.91                  1
3.07                  1
3.09                  1
3.11                  1
3.16                  1
3.17                  1
3.18                  4
3.2                   1
3.22                  2
3.23                  2
3.26                  1
3.27                  1
3.3                   2
3.32                  1
3.34                  1
3.37                  1
3.43                  1
3.47                  1
3.52                  1
3.55                  1
3.57                  1
3.58                  2
3.59                  3
3.67                  1
3.68                  1
3.7                   2
3.73                  1
3.74                  1
3.79                  2
3.91                  1
4.01                  2
4.13                  1
4.46                  2
4.49                  2
4.66                  1
4.68                  2
4.7                   1
4.73                  1
4.74                  1
4.83                  1
4.88                  1
4.89                  1
4.93                  1
4.95                  1
4.97                  2
4.98                  1
4.99                  1
5                     1
5.03                  1
5.05                  1
5.07                  1
5.27                  1
5.36                  1
5.41                  1
5.57                  1
5.61                  1
5.74                  1
5.97                  1
6.13                  1
6.16                  1
6.17                  1
6.29                  1
6.38                  1
6.4                   1
6.41                  1
6.59                  1
6.6                   1
6.61                  1
6.64                  1
6.67                  1
6.74                  1
6.77                  1
6.8                   1
7.05                  1
7.29                  1
7.53                  1
7.6                   1
7.72                  1
7.83                  1
7.93                  2
8.1                   1
8.29                  1
8.37                  1
8.82                  1
8.89                  1
9.02                  2
9.05                  1
9.23                  1
9.34                  1
9.91                  2

[279 rows x 1 columns]

In [16]:
merged_data_creatinine_b.index[0]

'   < 0.1'

In [17]:
merged_data_dropna['Creatinine(B)'].replace({'   < 0.1': 1}, inplace=True)
merged_data_dropna['Creatinine(B)'] = pd.to_numeric(merged_data_dropna['Creatinine(B)'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    float64
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    object
 22  tidal volume        359 non-null    object
 23  respiratory rate    486 non-null    object
 24  minute ventilation  331 non-null    object
 25  spo2                531 non-null    object
dtypes: float64(17), int64(3), object(6)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/3031552584.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['Creatinine(B)'].replace({'   < 0.1': 1}, inplace=True)
/tmp/ipykernel_19485/3031552584.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['Creatinine(B)'] = pd.to_numeric(merged_data_dropna['Creatinine(B)'])

In [18]:
merged_data_fio2 = merged_data_dropna['fio2'].value_counts().sort_index().to_frame()
merged_data_fio2

     fio2
100   146
21      2
22     19
23     10
24      8
25     10
26      2
28     12
30     16
32      5
34      1
35     81
35%     1
36      2
37      1
38      4
40     57
42      1
44      1
45      7
48      1
50     26
50%     1
55      5
56      1
60     32
65      2
70     20
80     25
83      1
85      2
90     12
95      1

[33 rows x 1 columns]

In [19]:
merged_data_dropna['fio2'].replace({'35%': 35}, inplace=True)
merged_data_dropna['fio2'].replace({'50%': 50}, inplace=True)
merged_data_dropna['fio2'] = pd.to_numeric(merged_data_dropna['fio2'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    float64
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    float64
 22  tidal volume        359 non-null    object
 23  respiratory rate    486 non-null    object
 24  minute ventilation  331 non-null    object
 25  spo2                531 non-null    object
dtypes: float64(18), int64(3), object(5)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/3012837193.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['fio2'].replace({'35%': 35}, inplace=True)
/tmp/ipykernel_19485/3012837193.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['fio2'].replace({'50%': 50}, inplace=True)
/tmp/ipykernel_19485/3012837193.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['fio2'] = pd.to_numeric(merged_data_dropna['fio2'])

In [20]:
merged_data_tidal_volume = merged_data_dropna['tidal volume'].value_counts().sort_index().to_frame()
merged_data_tidal_volume

      tidal volume
-                3
0.88             1
10               1
1056             2
158              1
201              1
226              1
231              1
234              1
238              1
24               1
250              1
253              1
255              1
270              1
279              1
292              1
296              1
30               1
300              1
301              1
302              1
303              1
311              1
312              1
313              1
316              2
321              1
323              1
324              1
325              1
332              1
338              1
339              2
340              1
349              1
350              1
352              1
354              1
356              1
360              3
362              1
365              1
366              1
370              1
372              1
374              1
376              1
377              1
381              1
388              1
389              1
390              2
392              2
394              1
396              1
397              1
398              1
400              3
402              1
409              1
410              1
411              1
414              2
415              2
417              2
420              2
421              2
424              2
425              2
426              1
427              2
429              1
430              3
431              2
432              1
433              1
434              3
435              1
437              1
440              1
442              1
443              1
448              2
449              2
450              3
451              1
453              2
456              3
458              1
459              2
460              4
461              1
465              5
468              2
469              1
470              1
472              1
473              1
475              1
476              2
479              1
480              2
482              1
483              1
484              1
485              3
486              2
488              5
489              3
490              1
493              2
494              3
495              1
497              1
498              2
499              1
500              4
501              4
502              1
503              1
505              2
507              1
508              3
509              4
510              7
511              2
513              1
515              2
516              1
517              1
518              2
519              2
520              2
521              2
522              2
523              2
524              3
525              2
527              1
528              1
530              2
531              1
532              3
533              1
541              1
542              2
545              2
546              2
548              2
550              2
553              1
555              1
556              1
558              2
562              1
563              2
567              1
568              1
570              2
573              1
576              1
577              2
578              1
579              2
580              2
581              1
583              1
584              1
585              1
586              2
587              4
588              1
590              1
596              2
603              1
608              2
609              1
610              3
611              1
614              1
617              1
619              2
622              1
623              1
624              1
626              1
628              1
630              1
632              1
636              1
640              1
642              1
646              2
647              1
650              7
653              1
655              1
658              1
664              2
667              1
668              1
674              2
676              3
677              1
679              2
681              1
689              1
694              1
695              1
700              1
710              1
712              1
713              1
720              1
722              1
723              1
727              1
730              1
742              1
750              1
755              1
763              2
780              2
786              1
787              1
793              1
839              1
840              2
848              1
856              1
862              1
88               1
880              1
936              1
957              1
98               1

[237 rows x 1 columns]

In [21]:
merged_data_dropna['tidal volume'].replace({'-': None}, inplace=True)
merged_data_dropna['tidal volume'] = pd.to_numeric(merged_data_dropna['tidal volume'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    float64
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    float64
 22  tidal volume        356 non-null    float64
 23  respiratory rate    486 non-null    object
 24  minute ventilation  331 non-null    object
 25  spo2                531 non-null    object
dtypes: float64(19), int64(3), object(4)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/2498409780.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['tidal volume'].replace({'-': None}, inplace=True)
/tmp/ipykernel_19485/2498409780.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['tidal volume'] = pd.to_numeric(merged_data_dropna['tidal volume'])

In [22]:
merged_data_respiratory_rate = merged_data_dropna['respiratory rate'].value_counts().sort_index().to_frame()
merged_data_respiratory_rate

     respiratory rate
10                  6
11                  2
12                 11
13                 11
14                 17
15                 10
16                 44
17                 11
18                 39
19                  9
20                100
21                 12
22                 21
23                 11
24                 18
25                  4
26                  7
27                  7
28                  8
29                  8
30                  7
31                  3
32                  9
33                  4
34                  3
35                  5
36                  2
37                  1
38                  7
39                  2
40                 10
41                  2
42                  4
43                  5
44                  5
45                  2
46                  5
48                  4
49                  1
50                  5
51                  5
52                  2
520                 1
53                  2
54                  3
55                  2
58                  7
59                  3
6                   1
60                  1
61                  2
62                  1
63                  2
64                  1
65                  4
68                  1
69                  1
7                   1
72                  1
74                  1
78                  1
8                   1

[62 rows x 1 columns]

In [23]:
merged_data_dropna['respiratory rate'] = pd.to_numeric(merged_data_dropna['respiratory rate'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    float64
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    float64
 22  tidal volume        356 non-null    float64
 23  respiratory rate    486 non-null    float64
 24  minute ventilation  331 non-null    object
 25  spo2                531 non-null    object
dtypes: float64(20), int64(3), object(3)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/2846284584.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['respiratory rate'] = pd.to_numeric(merged_data_dropna['respiratory rate'])

In [24]:
merged_data_minute_ventilation = merged_data_dropna['minute ventilation'].value_counts().sort_index().to_frame()
merged_data_minute_ventilation

      minute ventilation
.8                     1
0.82                   1
10                     3
10.0                   2
10.1                   5
10.2                   1
10.3                   4
10.4                   3
10.5                   1
10.6                   1
10.7                   7
10.8                   2
10.9                   3
11                     1
11.1                   4
11.2                   6
11.4                   3
11.5                   2
11.6                   3
11.7                   7
11.8                   3
11.9                   3
12                     2
12.0                   1
12.1                   2
12.2                   1
12.4                   4
12.6                   3
12.7                   1
12.9                   3
13.0                   2
13.2                   1
13.3                   1
13.4                   2
13.6                   2
13.7                   2
13.8                   2
14                     2
14.1                   1
14.2                   1
14.3                   1
14.4                   1
14.8                   1
14.9                   2
15                     2
15.0                   1
15.3                   2
15.6                   1
15.7                   1
15.8                   2
15.9                   1
16                     4
16.5                   1
16.6                   1
17.2                   2
17.3                   4
17.7                   1
17.9                   1
19.1                   1
19.6                   1
19.7                   1
2.0                    1
2.7                    1
21.4                   2
21.6                   1
22                     1
22.9                   1
24.9                   1
3.1                    1
3.2                    1
3.6                    1
3.7                    1
4.0                    1
4.09                   1
4.1                    1
4.4                    2
4.8                    1
4.87                   1
443/                   1
5                      1
5.1                    3
5.13                   1
5.3                    1
5.5                    1
5.69                   1
5.7                    2
5.85                   1
5.9                    2
6.0                    1
6.04                   1
6.1                    2
6.2                    3
6.26                   1
6.3                    1
6.4                    1
6.41                   1
6.46                   1
6.5                    2
6.6                    1
6.7                    5
6.8                    5
6.9                    3
7.0                    1
7.06                   1
7.1                    3
7.18                   1
7.2                    1
7.25                   1
7.3                    5
7.4                    5
7.5                    1
7.6                    3
7.64                   2
7.7                    5
7.72                   2
7.8                    4
7.81                   1
7.87                   1
7.9                    2
8.0                    3
8.1                    6
8.12                   1
8.16                   1
8.2                    5
8.3                    1
8.4                   10
8.43                   1
8.46                   1
8.5                    6
8.6                    3
8.7                    4
8.8                    2
8.9                    5
9                      4
9.0                    4
9.01                   1
9.06                   1
9.1                    4
9.2                    3
9.3                    2
9.34                   1
9.4                    5
9.5                    7
9.6                    5
9.62                   1
9.7                    6
9.8                    4
9.86                   1
9.9                    2

[149 rows x 1 columns]

In [25]:
merged_data_dropna['minute ventilation'].replace({'443/': 4.43}, inplace=True)
merged_data_dropna['minute ventilation'] = pd.to_numeric(merged_data_dropna['minute ventilation'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    float64
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    float64
 22  tidal volume        356 non-null    float64
 23  respiratory rate    486 non-null    float64
 24  minute ventilation  331 non-null    float64
 25  spo2                531 non-null    object
dtypes: float64(21), int64(3), object(2)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/2360466466.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['minute ventilation'].replace({'443/': 4.43}, inplace=True)
/tmp/ipykernel_19485/2360466466.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['minute ventilation'] = pd.to_numeric(merged_data_dropna['minute ventilation'])

In [26]:
merged_data_spo2 = merged_data_dropna['spo2'].value_counts().sort_index().to_frame()
merged_data_spo2

       spo2
100     255
63        1
82        1
83        1
86        1
88        1
88-93     1
89        1
90        2
91        3
91-96     1
92        6
92-94     1
93       16
94        7
95       25
96       27
97       30
98       56
99       57
POOR     34
poor      4

[22 rows x 1 columns]

In [27]:
merged_data_dropna['spo2'].replace({'88-93': 90.5}, inplace=True)
merged_data_dropna['spo2'].replace({'91-96': 93.5}, inplace=True)
merged_data_dropna['spo2'].replace({'92-94': 93}, inplace=True)
merged_data_dropna['spo2'].replace({'POOR': 50}, inplace=True)
merged_data_dropna['spo2'].replace({'poor': 50}, inplace=True)
merged_data_dropna['spo2'] = pd.to_numeric(merged_data_dropna['spo2'])
merged_data_dropna.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1871 entries, 0 to 12488
Data columns (total 26 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   病歷號                 1871 non-null   int64
 1   收件日期                1871 non-null   int64
 2   收件時間                1871 non-null   int64
 3   Temperature         1871 non-null   float64
 4   pH                  1871 non-null   float64
 5   pCO2                1871 non-null   float64
 6   pO2                 1871 non-null   float64
 7   HCO3                1871 non-null   float64
 8   TCO2                1870 non-null   float64
 9   ABE                 1871 non-null   float64
 10  SBE                 1871 non-null   float64
 11  SBC                 1871 non-null   float64
 12  SAT                 1871 non-null   float64
 13  Na                  682 non-null    float64
 14  K                   733 non-null    float64
 15  Mg                  107 non-null    float64
 16  Cl                  174 non-null    float64
 17  BUN (B)             509 non-null    float64
 18  Creatinine(B)       583 non-null    float64
 19  mode                538 non-null    object
 20  peep                487 non-null    float64
 21  fio2                515 non-null    float64
 22  tidal volume        356 non-null    float64
 23  respiratory rate    486 non-null    float64
 24  minute ventilation  331 non-null    float64
 25  spo2                531 non-null    float64
dtypes: float64(22), int64(3), object(1)
memory usage: 394.7+ KB

/tmp/ipykernel_19485/1865337238.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['spo2'].replace({'88-93': 90.5}, inplace=True)
/tmp/ipykernel_19485/1865337238.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['spo2'].replace({'91-96': 93.5}, inplace=True)
/tmp/ipykernel_19485/1865337238.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['spo2'].replace({'92-94': 93}, inplace=True)
/tmp/ipykernel_19485/1865337238.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['spo2'].replace({'POOR': 50}, inplace=True)
/tmp/ipykernel_19485/1865337238.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['spo2'].replace({'poor': 50}, inplace=True)
/tmp/ipykernel_19485/1865337238.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_data_dropna['spo2'] = pd.to_numeric(merged_data_dropna['spo2'])